name: Deploy to Crates.io
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    uses: travisbaars/actions-rs/.github/workflows/deploy-to-crates.yml@main
    secrets:
      token: ${{ secrets.CRATES_TOKEN }}
