name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-test:
    uses: travisbaars/actions-rs/.github/workflows/integration.yml@main
